# -*- coding: utf-8 -*-
"""whatsapp

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JKXWGEUZ65Nn8u1FX6_PPjc1p-ANcuGX
"""

import os

os.environ['DISPLAY'] = ':0'
import pywhatkit

# Send a WhatsApp Message to a Contact at 1:30 PM
#pywhatkit.sendwhatmsg("+910123456789", "Hi", 13, 30)

# Same as above but Closes the Tab in 2 Seconds after Sending the Message
#pywhatkit.sendwhatmsg("+910123456789", "Hi", 13, 30, 15, True, 2)

# Send an Image to a Group with the Caption as Hello
#pywhatkit.sendwhats_image("AB123CDEFGHijklmn", "Images/Hello.png", "Hello")

# Send an Image to a Contact with the no Caption
#pywhatkit.sendwhats_image("+910123456789", "Images/Hello.png")

# Send a WhatsApp Message to a Group at 12:00 AM
pywhatkit.sendwhatmsg_to_group("HcMePSyL4RzGxmICDYpgrf", "Hey All! sent from code", 11,10)

# Send a WhatsApp Message to a Group instantly
#pywhatkit.sendwhatmsg_to_group_instantly("PSI hackathon", "Hey All! sent from code",0)

# Play a Video on YouTube
#pywhatkit.playonyt("PyWhatKit")